In [1]:
import torch
from pywander.neural_network.generative_adversarial_network import GAN, generate_random, generate_real

Using cuda device


In [2]:
gan = GAN(data_features=4)
gan.to_device()

In [3]:
for i in range(10000):
    gan.train_one(generate_real(), torch.FloatTensor([1.0]))


trained by: Discriminator loss: 0.224360  train_counter:  3000
trained by: Discriminator loss: 0.169321  train_counter:  6000
trained by: Discriminator loss: 0.199179  train_counter:  9000
trained by: Discriminator loss: 0.236121  train_counter: 12000
trained by: Discriminator loss: 0.255821  train_counter: 15000
trained by: Discriminator loss: 0.263344  train_counter: 18000


In [4]:
for i in range(10):
    fake_input = torch.rand(1)
    result = gan.generator.forward(fake_input.to(gan.device))
    print(result)

tensor([0.9637, 0.0254, 0.9600, 0.0220], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9631, 0.0261, 0.9591, 0.0227], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9645, 0.0245, 0.9611, 0.0210], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9649, 0.0240, 0.9618, 0.0204], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9662, 0.0226, 0.9638, 0.0188], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9658, 0.0230, 0.9631, 0.0194], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9632, 0.0259, 0.9593, 0.0225], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9660, 0.0228, 0.9635, 0.0191], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9638, 0.0252, 0.9602, 0.0218], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9663, 0.0224, 0.9639, 0.0187], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
