In [1]:
import torch
from pywander.neural_network.generative_adversarial_network import GAN, generate_random, generate_real

Using cuda device


In [2]:
gan = GAN(data_features=4)
gan.to_device()

In [3]:
for i in range(10000):
    gan.train_one(generate_real(), torch.FloatTensor([1.0]))


trained by: Discriminator loss: 0.242195  train_counter:  3000
trained by: Discriminator loss: 0.189642  train_counter:  6000
trained by: Discriminator loss: 0.173138  train_counter:  9000
trained by: Discriminator loss: 0.217521  train_counter: 12000
trained by: Discriminator loss: 0.251278  train_counter: 15000
trained by: Discriminator loss: 0.261835  train_counter: 18000


In [4]:
for i in range(10):
    fake_input = torch.rand(1)
    result = gan.generator.forward(fake_input.to(gan.device))
    print(result)

tensor([0.9687, 0.0233, 0.9572, 0.0290], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9687, 0.0233, 0.9572, 0.0291], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9696, 0.0225, 0.9584, 0.0281], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9656, 0.0257, 0.9536, 0.0321], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9713, 0.0212, 0.9604, 0.0264], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9690, 0.0230, 0.9576, 0.0287], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9673, 0.0244, 0.9555, 0.0304], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9719, 0.0207, 0.9612, 0.0257], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9694, 0.0227, 0.9581, 0.0283], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
tensor([0.9686, 0.0234, 0.9571, 0.0291], device='cuda:0',
       grad_fn=<SigmoidBackward0>)
