## pytorch的张量
pytorch的张量和numpy的ndarray对象相比，多了GPU计算支持和自动微分支持。而在具体使用语法上非常相似，下面不会给出过多的解释，只是给出一些代码片段，看看输出是否是你心中想的。


In [1]:
import torch

In [2]:
t_1 = torch.arange(3*4*5)
print(t_1)
print(t_1.shape)
print(t_1.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59])
torch.Size([60])
1


In [3]:
t_1 = t_1.reshape(3,4,-1)
print(t_1)
print(t_1.shape)
print(t_1.ndim)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
torch.Size([3, 4, 5])
3


In [4]:
# zeros
t_2 = torch.zeros(3,4,5)
print(t_2)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [5]:
# ones
t_3 = torch.ones(3,4,5)
print(t_3)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [6]:
# rand是[0,1)的均匀分布采样
t_4 = torch.rand(3,4,5)
t_4

tensor([[[0.8113, 0.3394, 0.2720, 0.9207, 0.0957],
         [0.4811, 0.3076, 0.9587, 0.1539, 0.9291],
         [0.1717, 0.2102, 0.7829, 0.9354, 0.6514],
         [0.3664, 0.8242, 0.4934, 0.1438, 0.2941]],

        [[0.0441, 0.3608, 0.0146, 0.5653, 0.0251],
         [0.9815, 0.6901, 0.4134, 0.7310, 0.7277],
         [0.2793, 0.3744, 0.9256, 0.7317, 0.4547],
         [0.3886, 0.7216, 0.5853, 0.1700, 0.3274]],

        [[0.4683, 0.8302, 0.5207, 0.5959, 0.0076],
         [0.8260, 0.5574, 0.2004, 0.9668, 0.6882],
         [0.1189, 0.0598, 0.2422, 0.1047, 0.2615],
         [0.4006, 0.1177, 0.1680, 0.2726, 0.1412]]])

In [7]:
# randn是均值为0、标准差为1的标准正态分布采样
t_5 = torch.randn(3,4,5)
t_5

tensor([[[ 1.3702, -0.2107, -0.1919, -0.8309, -0.3276],
         [-1.9017, -0.9945, -0.9329, -0.0573, -0.4386],
         [ 0.2649, -0.6930, -0.2420, -1.6502,  0.4475],
         [ 0.4511, -0.6654,  1.1086, -2.5350, -0.9212]],

        [[ 1.3208,  0.1201,  0.5752,  1.4812, -1.1766],
         [-1.5987, -1.4406, -0.9006, -1.1557,  0.4850],
         [-0.9849,  0.0805,  1.2830,  1.0878,  0.5475],
         [ 1.1013,  0.0366, -2.4024, -1.1793, -0.7856]],

        [[ 0.2563,  0.4505,  0.5686, -1.3972,  1.9129],
         [-0.4102, -1.3756, -1.2572,  0.0318,  0.5648],
         [ 0.6800, -1.0321,  0.5484, -1.1757, -0.4194],
         [-0.6382,  3.1950,  0.5966,  0.0533, -1.3183]]])

## 单元素张量
单元素张量可以用 `item()` 来将该元素取出来，返回的是python对象。

In [8]:
t_6 = torch.tensor([5])
print(t_6.shape)
print(t_6.item())

torch.Size([1])
5


In [9]:
t_7 = t_3.sum()
print(t_7)
print(t_7.item())
print(type(t_7.item()))

tensor(60.)
60.0
<class 'float'>


## 按元素运算

In [10]:
torch.ones(3,4,5) * 2

tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]])

In [11]:
(torch.ones(3,4,5) * 2) + torch.ones(3,4,5)

tensor([[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]])

In [12]:
t_5 > 0

tensor([[[ True, False, False, False, False],
         [False, False, False, False, False],
         [ True, False, False, False,  True],
         [ True, False,  True, False, False]],

        [[ True,  True,  True,  True, False],
         [False, False, False, False,  True],
         [False,  True,  True,  True,  True],
         [ True,  True, False, False, False]],

        [[ True,  True,  True, False,  True],
         [False, False, False,  True,  True],
         [ True, False,  True, False, False],
         [False,  True,  True,  True, False]]])

## 索引和切片

In [13]:
t_1

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])

In [14]:
t_1[0,0,0]

tensor(0)

In [15]:
t_1[0,0,:]

tensor([0, 1, 2, 3, 4])

In [16]:
t_1[0,:,:]

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [17]:
print(t_2)
t_2[:,:,1] = 1
print(t_2)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
tensor([[[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]]])


## 对于维度的再思考
numpy和pytorch里面都有一个维度的概念，某些函数的运作可以指定一个dim参数，一维二维的情况还好，再多的维度试图从图形来理解并不是个好办法。下面提供了另外一种思路。

一个基本的思路是：将张量按照指定维度拆分，然后将这些拆分出来的张量应用目标函数。

### sum

In [18]:
t_1

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])

In [19]:
t_1[0]

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [20]:
t_1[1]

tensor([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]])

In [21]:
t_1[2]

tensor([[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]])

In [22]:
# = t_1[0]+t_1[1]+t_1[2]
t_1.sum(dim=0)

tensor([[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87],
        [ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]])

### argmax

In [23]:
t_4

tensor([[[0.8113, 0.3394, 0.2720, 0.9207, 0.0957],
         [0.4811, 0.3076, 0.9587, 0.1539, 0.9291],
         [0.1717, 0.2102, 0.7829, 0.9354, 0.6514],
         [0.3664, 0.8242, 0.4934, 0.1438, 0.2941]],

        [[0.0441, 0.3608, 0.0146, 0.5653, 0.0251],
         [0.9815, 0.6901, 0.4134, 0.7310, 0.7277],
         [0.2793, 0.3744, 0.9256, 0.7317, 0.4547],
         [0.3886, 0.7216, 0.5853, 0.1700, 0.3274]],

        [[0.4683, 0.8302, 0.5207, 0.5959, 0.0076],
         [0.8260, 0.5574, 0.2004, 0.9668, 0.6882],
         [0.1189, 0.0598, 0.2422, 0.1047, 0.2615],
         [0.4006, 0.1177, 0.1680, 0.2726, 0.1412]]])

In [24]:
t_4[:,0,:]

tensor([[0.8113, 0.3394, 0.2720, 0.9207, 0.0957],
        [0.0441, 0.3608, 0.0146, 0.5653, 0.0251],
        [0.4683, 0.8302, 0.5207, 0.5959, 0.0076]])

In [25]:
t_4[:,1,:]

tensor([[0.4811, 0.3076, 0.9587, 0.1539, 0.9291],
        [0.9815, 0.6901, 0.4134, 0.7310, 0.7277],
        [0.8260, 0.5574, 0.2004, 0.9668, 0.6882]])

In [26]:
t_4[:,2,:]

tensor([[0.1717, 0.2102, 0.7829, 0.9354, 0.6514],
        [0.2793, 0.3744, 0.9256, 0.7317, 0.4547],
        [0.1189, 0.0598, 0.2422, 0.1047, 0.2615]])

In [27]:
t_4[:,3,:]

tensor([[0.3664, 0.8242, 0.4934, 0.1438, 0.2941],
        [0.3886, 0.7216, 0.5853, 0.1700, 0.3274],
        [0.4006, 0.1177, 0.1680, 0.2726, 0.1412]])

In [28]:
# =argmax(t_4[:,0,:],t_4[:,1,:],t_4[:,2,:],t_4[:,3,:])
t_4.argmax(dim=1)

tensor([[0, 3, 1, 2, 1],
        [1, 3, 2, 2, 1],
        [1, 0, 0, 1, 1]])

即使是最简单的情况，因为批量处理的存在，神经网络的一个输出可能是这样的：

In [29]:
# 第一个维度存储的样本计数
t_8 = torch.rand(32,10)

In [30]:
t_8.argmax(dim=1)

tensor([4, 6, 7, 1, 2, 9, 2, 4, 4, 7, 7, 8, 9, 1, 2, 2, 0, 7, 7, 6, 9, 0, 8, 8,
        5, 4, 6, 4, 7, 7, 3, 9])

In [31]:
t_8[:,0]

tensor([0.2131, 0.6024, 0.3581, 0.6646, 0.4971, 0.8565, 0.1846, 0.7581, 0.4805,
        0.9173, 0.8863, 0.6624, 0.4382, 0.8482, 0.6016, 0.7282, 0.9545, 0.0485,
        0.3723, 0.4181, 0.0277, 0.8681, 0.4732, 0.3896, 0.8014, 0.8284, 0.2809,
        0.8951, 0.8465, 0.4928, 0.5625, 0.2149])

In [32]:
t_8[:,1]

tensor([0.0336, 0.5129, 0.6291, 0.9438, 0.7302, 0.8149, 0.3268, 0.5691, 0.7621,
        0.9023, 0.0142, 0.6073, 0.6022, 0.9698, 0.5560, 0.5511, 0.0410, 0.4358,
        0.8208, 0.9180, 0.7810, 0.7887, 0.9228, 0.3740, 0.4470, 0.5264, 0.2442,
        0.5503, 0.0455, 0.1221, 0.3526, 0.6658])

按照上面的分析，就能理解为什么 `t_8.argmax(dim=1)` 的值的含义就是一个样本的输出的最大值索引。

### cat
cat用于张量连接，一般需要指定按照那个维度来连接。

In [33]:
t_9 = torch.arange(12, dtype=torch.float32).reshape((3,4))
print(t_9)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [34]:
t_10 = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(t_10)

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


In [35]:
torch.cat((t_9, t_10), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [36]:
t_9[0]

tensor([0., 1., 2., 3.])

In [37]:
t_9[1]

tensor([4., 5., 6., 7.])

In [38]:
t_10[0]

tensor([2., 1., 4., 3.])

In [39]:
t_10[1]

tensor([1., 2., 3., 4.])

可以理解为上面的输出按照维度=0拼接。

In [40]:
torch.cat((t_9,t_10), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [41]:
t_9[:,0]

tensor([0., 4., 8.])

In [42]:
t_9[:,1]

tensor([1., 5., 9.])

In [43]:
t_10[:,0]

tensor([2., 1., 4.])

In [44]:
t_10[:,1]

tensor([1., 2., 3.])

拼接的情况太复杂了，参考上面的运行代码大概会有个概念。

## 和numpy进行数据交换
```
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
```

```
t = torch.ones(5)
n = t.numpy()
```

## 节省内存的原地修改
用索引和切片对张量进行操作就是原地修改的，pytorch里面有些方法也是原地修改的，这里要说的主要是基于python的赋值语句：`x = x + 1` ,python的内在机制是如果变量是可变对象，那么修改之后变量对象是会重新创建的，这在这边大型张量环境下可能是个问题了。

In [45]:
print(t_2)
print(id(t_2))

tensor([[[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]]])
2175214939712


In [46]:
t_2 = t_2 + 1
print(id(t_2))

2175214942752


可以通过切片语法来实现原地修改，节省内存开销。

In [47]:
print(t_2)
print(id(t_2))

tensor([[[1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.]],

        [[1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.]],

        [[1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.]]])
2175214942752


In [48]:
t_2[:] = t_2 + 1
print(id(t_2))

2175214942752


## 广播机制
类似numpy，pytorch这边也有广播机制，这里也不做过多介绍了，并不鼓励这样的编码风格。

In [49]:
t_11 = torch.arange(3).reshape((3, 1))
t_12 = torch.arange(2).reshape((1, 2))
print(t_11)
print(t_12)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [50]:
torch.broadcast_tensors(t_11, t_12)

(tensor([[0, 0],
         [1, 1],
         [2, 2]]),
 tensor([[0, 1],
         [0, 1],
         [0, 1]]))

In [51]:
t_11 + t_12

tensor([[0, 1],
        [1, 2],
        [2, 3]])