## pytorch的张量
pytorch的张量和numpy的ndarray对象相比，多了GPU计算支持和自动微分支持。而在具体使用语法上非常相似，下面不会给出过多的解释，只是给出一些代码片段，看看输出是否是你心中想的。然后为了增加难度，下面的例子都是基于三维数组或三维张量的，在numpy学习中虽然对维度或轴的概念有所讨论，但还有不清晰的地方，而下面的例子会增加更多关于多维张量对于不同维度下的操作的例子，来巩固关于维度的概念认识。


In [1]:
import torch

In [2]:
t_1 = torch.arange(3*4*5)
print(t_1)
print(t_1.shape)
print(t_1.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59])
torch.Size([60])
1


In [3]:
t_1 = t_1.reshape(3,4,-1)
print(t_1)
print(t_1.shape)
print(t_1.ndim)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
torch.Size([3, 4, 5])
3


In [4]:
# zeros
t_2 = torch.zeros(3,4,5)
print(t_2)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [5]:
# ones
t_3 = torch.ones(3,4,5)
print(t_3)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [6]:
# rand是[0,1)的均匀分布采样
t_4 = torch.rand(3,4,5)
t_4

tensor([[[0.9591, 0.7805, 0.1832, 0.9778, 0.5701],
         [0.5727, 0.6393, 0.6210, 0.8258, 0.7200],
         [0.4206, 0.8784, 0.5067, 0.4370, 0.6536],
         [0.7615, 0.1032, 0.1864, 0.4418, 0.0425]],

        [[0.9602, 0.7479, 0.1072, 0.4155, 0.4677],
         [0.2439, 0.3598, 0.9582, 0.5439, 0.0049],
         [0.3712, 0.4989, 0.9907, 0.2396, 0.6040],
         [0.3541, 0.1247, 0.3067, 0.0287, 0.2035]],

        [[0.2149, 0.7138, 0.2733, 0.2306, 0.2903],
         [0.4126, 0.1004, 0.0186, 0.4085, 0.2176],
         [0.8045, 0.9717, 0.5300, 0.5964, 0.0284],
         [0.4018, 0.5685, 0.6582, 0.9032, 0.1596]]])

In [7]:
# randn是均值为0、标准差为1的标准正态分布采样
t_5 = torch.randn(3,4,5)
t_5

tensor([[[ 0.8329, -1.0569,  0.3654, -1.3916,  1.6998],
         [-0.5710, -1.1047,  0.3352, -0.9737,  1.2224],
         [ 0.3886,  2.7589,  0.9745, -2.1717, -0.5654],
         [-0.2131,  0.9637, -0.9736,  0.2258,  0.5001]],

        [[ 1.0111,  0.4891, -0.5739,  0.1086, -1.4090],
         [ 0.4589,  0.6775,  0.4539, -0.7697,  0.6262],
         [-0.7611,  0.5675,  0.2772,  1.3586, -0.3607],
         [ 0.6609,  0.7658, -1.1333,  0.7950,  2.4345]],

        [[-1.5311,  1.6685, -0.9046, -0.3233,  2.4309],
         [ 0.9631, -1.2094, -0.3847, -0.2302,  0.0982],
         [ 0.1748, -1.5426,  0.5219,  1.3923,  0.9860],
         [ 0.2124, -0.6483, -0.6837,  0.0768, -0.5100]]])

## 单元素张量
单元素张量可以用 `item()` 来将该元素取出来，返回的是python对象。

In [8]:
t_6 = torch.tensor([5])
print(t_6.shape)
print(t_6.item())

torch.Size([1])
5


In [9]:
t_7 = t_3.sum()
print(t_7)
print(t_7.item())
print(type(t_7.item()))

tensor(60.)
60.0
<class 'float'>


## 按元素运算

In [10]:
torch.ones(3,4,5) * 2

tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]])

In [11]:
(torch.ones(3,4,5) * 2) + torch.ones(3,4,5)

tensor([[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]])

In [12]:
t_5 > 0

tensor([[[ True, False,  True, False,  True],
         [False, False,  True, False,  True],
         [ True,  True,  True, False, False],
         [False,  True, False,  True,  True]],

        [[ True,  True, False,  True, False],
         [ True,  True,  True, False,  True],
         [False,  True,  True,  True, False],
         [ True,  True, False,  True,  True]],

        [[False,  True, False, False,  True],
         [ True, False, False, False,  True],
         [ True, False,  True,  True,  True],
         [ True, False, False,  True, False]]])

## 索引和切片

In [13]:
t_1

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])

In [14]:
t_1[0,0,0]

tensor(0)

In [15]:
t_1[0,0,:]

tensor([0, 1, 2, 3, 4])

In [16]:
t_1[0,:,:]

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [17]:
print(t_2)
t_2[:,:,1] = 1
print(t_2)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
tensor([[[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]]])


## 对于维度的再思考
numpy和pytorch里面都有一个维度的概念，某些函数的运作可以指定一个dim参数，一维二维的情况还好，再多的维度试图从图形来理解并不是个好办法。下面提供了另外一种思路。

一个基本的思路是：将张量按照指定维度拆分，然后将这些拆分出来的张量应用目标函数。

### sum

In [18]:
t_1

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])

In [19]:
t_1[0]

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [20]:
t_1[1]

tensor([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]])

In [21]:
t_1[2]

tensor([[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]])

In [22]:
# = t_1[0]+t_1[1]+t_1[2]
t_1.sum(dim=0)

tensor([[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87],
        [ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]])

### argmax

In [23]:
t_4

tensor([[[0.9591, 0.7805, 0.1832, 0.9778, 0.5701],
         [0.5727, 0.6393, 0.6210, 0.8258, 0.7200],
         [0.4206, 0.8784, 0.5067, 0.4370, 0.6536],
         [0.7615, 0.1032, 0.1864, 0.4418, 0.0425]],

        [[0.9602, 0.7479, 0.1072, 0.4155, 0.4677],
         [0.2439, 0.3598, 0.9582, 0.5439, 0.0049],
         [0.3712, 0.4989, 0.9907, 0.2396, 0.6040],
         [0.3541, 0.1247, 0.3067, 0.0287, 0.2035]],

        [[0.2149, 0.7138, 0.2733, 0.2306, 0.2903],
         [0.4126, 0.1004, 0.0186, 0.4085, 0.2176],
         [0.8045, 0.9717, 0.5300, 0.5964, 0.0284],
         [0.4018, 0.5685, 0.6582, 0.9032, 0.1596]]])

In [24]:
t_4[:,0,:]

tensor([[0.9591, 0.7805, 0.1832, 0.9778, 0.5701],
        [0.9602, 0.7479, 0.1072, 0.4155, 0.4677],
        [0.2149, 0.7138, 0.2733, 0.2306, 0.2903]])

In [25]:
t_4[:,1,:]

tensor([[0.5727, 0.6393, 0.6210, 0.8258, 0.7200],
        [0.2439, 0.3598, 0.9582, 0.5439, 0.0049],
        [0.4126, 0.1004, 0.0186, 0.4085, 0.2176]])

In [26]:
t_4[:,2,:]

tensor([[0.4206, 0.8784, 0.5067, 0.4370, 0.6536],
        [0.3712, 0.4989, 0.9907, 0.2396, 0.6040],
        [0.8045, 0.9717, 0.5300, 0.5964, 0.0284]])

In [27]:
t_4[:,3,:]

tensor([[0.7615, 0.1032, 0.1864, 0.4418, 0.0425],
        [0.3541, 0.1247, 0.3067, 0.0287, 0.2035],
        [0.4018, 0.5685, 0.6582, 0.9032, 0.1596]])

In [28]:
# =argmax(t_4[:,0,:],t_4[:,1,:],t_4[:,2,:],t_4[:,3,:])
t_4.argmax(dim=1)

tensor([[0, 2, 1, 0, 1],
        [0, 0, 2, 1, 2],
        [2, 2, 3, 3, 0]])

即使是最简单的情况，因为批量处理的存在，神经网络的一个输出可能是这样的：

In [29]:
# 第一个维度存储的样本计数
t_8 = torch.rand(32,10)
print(t_8)

tensor([[0.4902, 0.6946, 0.0139, 0.9022, 0.7996, 0.4757, 0.5094, 0.0212, 0.8062,
         0.0703],
        [0.4700, 0.8158, 0.3337, 0.0952, 0.7728, 0.0825, 0.4175, 0.6852, 0.2696,
         0.0349],
        [0.4462, 0.8509, 0.8168, 0.9507, 0.0070, 0.7057, 0.8904, 0.6736, 0.2686,
         0.7722],
        [0.8587, 0.8703, 0.4061, 0.9965, 0.6060, 0.2984, 0.2297, 0.2281, 0.7751,
         0.1337],
        [0.0977, 0.2662, 0.9287, 0.5681, 0.4454, 0.2427, 0.7583, 0.5844, 0.7678,
         0.5011],
        [0.2047, 0.9886, 0.1651, 0.9053, 0.2849, 0.0948, 0.8249, 0.4567, 0.3832,
         0.7760],
        [0.8068, 0.9956, 0.9873, 0.0414, 0.0709, 0.7108, 0.3767, 0.0520, 0.7823,
         0.3459],
        [0.4292, 0.5894, 0.9248, 0.6396, 0.3892, 0.7812, 0.2213, 0.8578, 0.3397,
         0.6944],
        [0.8805, 0.1064, 0.9994, 0.2305, 0.6669, 0.9244, 0.2218, 0.9122, 0.8185,
         0.4052],
        [0.5308, 0.8049, 0.4376, 0.8305, 0.2441, 0.3586, 0.2453, 0.7767, 0.5278,
         0.5357],
        [0

In [30]:
t_8.argmax(dim=1)

tensor([3, 1, 3, 3, 2, 1, 1, 2, 2, 3, 2, 0, 9, 1, 2, 9, 6, 6, 9, 3, 6, 7, 3, 3,
        9, 9, 6, 2, 7, 3, 9, 4])

In [31]:
t_8[:,0]

tensor([0.4902, 0.4700, 0.4462, 0.8587, 0.0977, 0.2047, 0.8068, 0.4292, 0.8805,
        0.5308, 0.7981, 0.9654, 0.7651, 0.3505, 0.8650, 0.8340, 0.4073, 0.0466,
        0.8018, 0.2706, 0.2060, 0.0410, 0.3252, 0.3004, 0.2037, 0.4491, 0.6657,
        0.9071, 0.2103, 0.8953, 0.7761, 0.7915])

In [32]:
t_8[:,1]

tensor([0.6946, 0.8158, 0.8509, 0.8703, 0.2662, 0.9886, 0.9956, 0.5894, 0.1064,
        0.8049, 0.6056, 0.1576, 0.3459, 0.9660, 0.2967, 0.5649, 0.2100, 0.4913,
        0.0858, 0.4063, 0.4101, 0.4943, 0.3249, 0.4640, 0.3447, 0.6123, 0.3139,
        0.8880, 0.5418, 0.3636, 0.2521, 0.1875])

按照上面的分析，就能理解为什么 `t_8.argmax(dim=1)` 的值的含义就是一个样本的输出的最大值索引。

### cat
cat用于张量连接，一般需要指定按照那个维度来连接。

In [33]:
t_9 = torch.arange(12, dtype=torch.float32).reshape((3,4))
print(t_9)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [34]:
t_10 = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(t_10)

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


In [35]:
torch.cat((t_9, t_10), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [36]:
t_9[0]

tensor([0., 1., 2., 3.])

In [37]:
t_9[1]

tensor([4., 5., 6., 7.])

In [38]:
t_10[0]

tensor([2., 1., 4., 3.])

In [39]:
t_10[1]

tensor([1., 2., 3., 4.])

可以理解为上面的输出按照维度=0拼接。

In [40]:
torch.cat((t_9,t_10), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [41]:
t_9[:,0]

tensor([0., 4., 8.])

In [42]:
t_9[:,1]

tensor([1., 5., 9.])

In [43]:
t_10[:,0]

tensor([2., 1., 4.])

In [44]:
t_10[:,1]

tensor([1., 2., 3.])

拼接的情况太复杂了，参考上面的运行代码大概会有个概念。

## 和numpy进行数据交换
```
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
```

```
t = torch.ones(5)
n = t.numpy()
```

## 节省内存的原地修改
用索引和切片对张量进行操作就是原地修改的，pytorch里面有些方法也是原地修改的，这里要说的主要是基于python的赋值语句：`x = x + 1` ,python的内在机制是如果变量是可变对象，那么修改之后变量对象是会重新创建的，这在这边大型张量环境下可能是个问题了。

In [45]:
print(t_2)
print(id(t_2))

tensor([[[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]]])
1681409032912


In [46]:
t_2 = t_2 + 1
print(id(t_2))

1679798334112


可以通过切片语法来实现原地修改，节省内存开销。

In [47]:
print(t_2)
print(id(t_2))

tensor([[[1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.]],

        [[1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.]],

        [[1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.],
         [1., 2., 1., 1., 1.]]])
1679798334112


In [48]:
t_2[:] = t_2 + 1
print(id(t_2))

1679798334112
